apiVersion: v1
kind: Service
metadata:
  name: termai-rerank
  namespace: term-ai
  labels:
    app: termai-rerank
spec:
  type: ClusterIP
  selector:
    app: termai-rerank
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
